org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# --- Minecraft / Fabric ---
# 26.x ships UNOBFUSCATED. No Yarn, no intermediary, no remapping.
minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.153.0+26.2
loom_version=1.16.2

# --- Mod ---
mod_version=1.0.0
maven_group=com.thefuncraft
archives_base_name=voltclient

# --- Optional integrations ---
modmenu_version=20.0.0-beta.4
